---
# tasks file for setup-apache-role
- name: Install httpd package
  yum:
    name: "{{ httpd_package_name }}"
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: Install apache2 package
  apt:
    name: "{{ apache2_package_name }}"
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html
    mode: 0666
